### ISSUE TITLE
Generación errónea del XML

### ISSUE THREAD

**Issue by jgomez14** [carlosrzdr/Practica1DIS#3]
Cuando se genera un XML con el programa si hay nodos que no tienen ningún elemento dentro aparecen como una etiqueta de cierre simplemente. Habría que generar estos nodos cuando se creara su primer elemento hijo

**Comment by pchazarra** [comment]
Buena observación, ahora mismo lo arreglamos.

**Comment by pchazarra** [comment]
It is fixed, can be found in fix_Generating_XML
