### ISSUE TITLE
Rama con carpeta de proyecto anterior

### ISSUE THREAD

**Issue by jgomez14** [carlosrzdr/Practica1DIS#7]
La rama LoadFile todavía tiene la carpeta de proyecto anterior a la que estamos usando ahora y no ha sido mergeada a develop antes del cambio mencionado. La funcionalidad añadida en esa rama se tiene que añadir desde una nueva rama que salga desde develop.

**Comment by pmj99** [comment]
Se ha creado una nueva rama desde develop llamada continue_with_file que contiene la misma funcionalidad que contenía la rama LoadFile por lo que el problema ya está resuelto
